import type { Metadata, Viewport } from 'next';
import { Inter, Space_Grotesk, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { Analytics } from '@vercel/analytics/react';
import { ThemeProvider } from './providers';
import { TransitionProvider } from '@/components/world/TransitionProvider';
import { profile } from '@/lib/data';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap'
});

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap'
});

const mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap'
});

const title = `${profile.name} — Solutions Architect & Technical Lead`;

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : profile.siteUrl
  ),
  title,
  description: profile.tagline,
  keywords: [
    'Keshav Krishan Sharma',
    'Solutions Architect',
    'Systems Architect',
    'Technical Lead',
    'Full Stack Engineer',
    'Multi-tenant SaaS',
    'Yii2',
    'React',
    'Next.js',
    'Prompt Engineer',
    'Gen AI Developer',
    'Agentic AI',
    'Portfolio'
  ],
  authors: [{ name: profile.name, url: profile.siteUrl }],
  creator: profile.name,
  alternates: { canonical: profile.siteUrl },
  openGraph: {
    title,
    description: profile.tagline,
    url: profile.siteUrl,
    siteName: `${profile.name} · Portfolio`,
    type: 'website',
    locale: 'en_IN'
    // Social share image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title,
    description: profile.tagline
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large' }
  }
};

// JSON-LD structured data — helps Google render a rich "Person" result.
const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: profile.name,
  url: profile.siteUrl,
  email: `mailto:${profile.email}`,
  jobTitle: 'Solutions Architect & Technical Lead',
  address: { '@type': 'PostalAddress', addressLocality: profile.location },
  sameAs: [profile.socials.linkedin, profile.socials.github],
  knowsAbout: [
    'Software Architecture',
    'Multi-tenant SaaS',
    'Yii2',
    'React',
    'TypeScript',
    'RBAC',
    'Generative AI'
  ]
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f8fafc' },
    { media: '(prefers-color-scheme: dark)', color: '#08081a' }
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${grotesk.variable} ${mono.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Prevent theme flash by syncing data-theme before paint */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var sysDark=window.matchMedia('(prefers-color-scheme: dark)').matches;var theme=t||(sysDark?'dark':'light');document.documentElement.setAttribute('data-theme',theme);}catch(e){}})();`
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
      </head>
      <body className="relative overflow-x-hidden">
        <ThemeProvider>
          <TransitionProvider>{children}</TransitionProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
